version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - docker build -t $ECR_REPOSITORY_URI:latest -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s:%s"}]' $IMAGE_DEF_NAME $ECR_REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
